### ISSUE TITLE
展示“暂不支持中国大陆以外的号码”后可以自动返回输入手机号页面

### ISSUE THREAD

**Issue by Mingle-2012** [llipengda/prosperage#1]
One can be enhanced

**Comment by llipengda** [comment]
修了捏，但是还没传

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: CrazyForLove ***@***.***>
Sent: Thursday, March 14, 2024 7:28:44 PM
To: llipengda/prosperage ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [llipengda/prosperage] 展示“暂不支持中国大陆以外的号码”后可以自动返回输入手机号页面 (Issue #1)


One can be enhanced

―

**Comment by llipengda** [comment]
修了
